# Generated by Django 4.2.16 on 2026-02-27 15:21

import chamados.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=64, unique=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente / Local')),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], default='aberto', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('tipo_compartilhamento', models.CharField(choices=[('publico', 'Link Público'), ('temporario', 'Link Temporário'), ('protegido', 'Protegido por Senha')], default='publico', max_length=20, verbose_name='Tipo de Compartilhamento')),
                ('senha_compartilhamento', models.CharField(blank=True, help_text='Necessário quando o tipo é "Protegido por Senha".', max_length=128, verbose_name='Senha do Link')),
                ('expira_em', models.DateTimeField(blank=True, help_text='Necessário quando o tipo é "Link Temporário".', null=True, verbose_name='Expira em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=chamados.models.video_upload_path, verbose_name='Arquivo de Vídeo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome Original')),
                ('tamanho', models.BigIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('descricao', models.CharField(blank=True, max_length=300, verbose_name='Descrição do vídeo')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='chamados.chamado')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeos',
                'ordering': ['-enviado_em'],
            },
        ),
    ]
