# Generated by Django 4.2.16 on 2026-02-27 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='endereco',
        ),
        migrations.AlterField(
            model_name='chamado',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentário')),
                ('autor_nome', models.CharField(blank=True, help_text='Identificação opcional para visitantes externos', max_length=100, verbose_name='Nome do Autor')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('autor_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='chamados.chamado')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['criado_em'],
            },
        ),
    ]
